rm -rf motorAcs
rm -rf motorAcsTech80
rm -rf motorAerotech
rm -rf motorAMCI
rm -rf motorAttocube
rm -rf motorDeltaTau
rm -rf motorFaulhaber
rm -rf motorHytec
rm -rf motorIms
rm -rf motorKohzu
rm -rf motorMclennan
rm -rf motorMicos
rm -rf motorMicroMo
rm -rf motorMicronix
rm -rf motorMotorSim
rm -rf motorMXmotor
rm -rf motorNewFocus
rm -rf motorNPoint
rm -rf motorOms
rm -rf motorOmsAsyn
rm -rf motorOriel
rm -rf motorParker
rm -rf motorPhytron
rm -rf motorPI
rm -rf motorPIGCS2
rm -rf motorPiJena
rm -rf motorScriptMotor
rm -rf motorSmarAct
rm -rf motorSmartMotor
rm -rf motorThorLabs
